name: ci

permissions: {}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15-intel, macos-latest, windows-latest, ubuntu-latest, ubuntu-24.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/setup-node@v4
      - uses: oven-sh/setup-bun@v2
      - if: ${{ matrix.os == 'macos-latest' || matrix.os == 'macos-15-intel' }}
        run: brew install automake libtool
      - if: ${{ matrix.os == 'windows-latest' }}
        name: Setup vcpkg and install libiconv
        run: |
          $vcpkgPath = "C:\vcpkg"
          if (-not (Test-Path $vcpkgPath)) {
            git clone https://github.com/Microsoft/vcpkg.git $vcpkgPath
            & $vcpkgPath\bootstrap-vcpkg.bat
          }
          & $vcpkgPath\vcpkg install libiconv
          echo "CMAKE_TOOLCHAIN_FILE=$vcpkgPath/scripts/buildsystems/vcpkg.cmake" >> $env:GITHUB_ENV
      - run: bun init-submodules
      # - run: bun configure
      - run: bun install --frozen-lockfile
      - run: bun run typecheck
      - run: bun run test:node
      - if: ${{ matrix.os == 'macos-latest' || matrix.os == 'macos-15-intel' }}
        run: bun run test:bun
