name: release

permissions:
  id-token: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/setup-node@v4
      - uses: oven-sh/setup-bun@v2
      - if: ${{ matrix.os == 'macos-latest' || matrix.os == 'macos-15-intel' }}
        run: brew install automake libtool
      - if: ${{ matrix.os == 'windows-latest' }}
        name: Download and extract libiconv
        run: |
          $libiconvUrl = "https://github.com/pffang/libiconv-for-Windows/releases/download/1.18/libiconv-for-Windows_prebuilt.zip"
          $libiconvZip = "$env:RUNNER_TEMP\libiconv.zip"
          $libiconvPath = "C:\libiconv"
          Invoke-WebRequest -Uri $libiconvUrl -OutFile $libiconvZip
          Expand-Archive -Path $libiconvZip -DestinationPath $libiconvPath -Force
          echo "LIBICONV_ROOT=$libiconvPath\libiconv-for-Windows_prebuilt" >> $env:GITHUB_ENV
      - run: bun init-submodules
      - if: ${{ matrix.os == 'windows-latest' }}
        run: npm install --global node-gyp
      - run: bun install --frozen-lockfile
      - run: bun run prebuildify
      - uses: actions/upload-artifact@v4
        with:
          name: libxmljs2-prebuilds-${{ matrix.os }}-x64+arm64
          path: "prebuilds/**/*.node"

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
      - uses: oven-sh/setup-bun@v2
      - uses: actions/download-artifact@v4
        with:
          pattern: libxmljs2-prebuilds-*
          path: prebuilds
          merge-multiple: true
      - run: tree prebuilds
      - run: npm publish --no-git-checks
